name: Deploy Docker image to Cloud run

on: 
  push:
    branches:
      - 'master'
jobs:
  build:
    name: Cloud Run Deployment
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@master

      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@master
        with:
          version: 'latest'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        run: |
          gcloud auth configure-docker
      
      - name: Build
        run: |
          docker build -t gcr.io/nomad-learninig/staffzo:latest .

      - name: Push
        run: |
          docker push gcr.io/nomad-learninig/staffzo:latest

      - name: Deploy
        run: |
          gcloud run deploy stuffzo \
          --region europe-west1 \
          --set-env-vars TOPIC_SUFFIX=olber \
          --image gcr.io/nomad-learninig/staffzo:latest \
          --platform managed \
          --allow-unauthenticated \
          --project nomad-learninig
